### ISSUE TITLE
preserve type for undefined

### ISSUE THREAD

**Issue by Guria** [cerebral/urlon#10]
`undefined` values now parse back as string, it potentially could break something:

``` js
var obj = { foo: undefined }
assert.deepEqual(parse(stringify(obj)), obj) // fail: { foo: 'undefined' } expected to be { foo: undefined }
```

I want to fix this as part of 3.0 release since it is could be breaking for someone.

**Comment by Guria** [comment]
cc @vjeux

**Comment by vjeux** [comment]
I don't think that undefined should be encoded at all. I see undefined as "does not exists".

**Comment by Guria** [comment]
yeah, it should be just like JSON, so undefined keys shouldn't stringified at all. do you agree?

**Comment by vjeux** [comment]
I agree

**Comment by borisirota** [comment]
@Guria Any estimation for the 3.0 release and this fix ?

**Comment by Guria** [comment]
Was busy for a while. I can plan it for a near future if you need this.

**Comment by borisirota** [comment]
Not that urgent. Its nice to have the expected behavior instead of manually checking undefined values before sending to `urlon` :)

When you'll have some time my friend. Thanks !
