### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by Guria** [cerebral/urlon#14]
@vjeux 
I just found out that we have no License defined for this project.
I'd like to add one but I feel like it is good to consult with you as original author of the code.
My suggestion is to use https://choosealicense.com/licenses/unlicense/ which grants all permissions to a public domain.
Do you agree or do you have any other preference?

**Comment by vjeux** [comment]
Hey, I'm happy with whatever license. In the open source I've seen MIT be the de-facto standard for those kind of projects.

**Comment by vjeux** [comment]
Feel free to merge if you're fine with it. https://github.com/cerebral/urlon/pull/15
