### ISSUE TITLE
Is there any RFC about urlon?

### ISSUE THREAD

**Issue by ghost** [cerebral/urlon#20]
Hi all. 

I would like to know if there is any RFC about urlon. So... Is there any RFC about urlon? would it be possible to have an RFC from urlon?

<br/>

*I'm thinking of creating a urlon based implementation but with some technical differences or design.*

**Comment by vjeux** [comment]
Not as far as I know. Feel free to create one!

**Comment by ghost** [comment]
Hi vjeux. thank you for feedback. I will close this issue then.
