### ISSUE TITLE
does cycle.js is used somehow?

### ISSUE THREAD

**Issue by Guria** [cerebral/urlon#8]
@vjeux can't see  https://github.com/vjeux/URLON/blob/master/src/cycle.js to be used anywhere. Do we need it?

**Comment by vjeux** [comment]
Urlon doesn't terminate if there's a cycle. I added this as a check but it was pretty invasive so removed it. Fortunately most js engines support weakmap now so we can make this cycle check faster

**Comment by Guria** [comment]
so we can safely remove it from src?

**Comment by vjeux** [comment]
Yes
