### ISSUE TITLE
repo maintain plans

### ISSUE THREAD

**Issue by Guria** [cerebral/urlon#9]
test runner doesn't work, since some resources is not available.
we need to rewrite tests using runner from npm.

**Comment by Guria** [comment]
* [ ] lint: https://github.com/feross/standard
* [ ] tests: test runner from npm
* [ ] travis
* [ ] src in common js only with `'use strict'`
* [ ] umd build with https://www.npmjs.com/package/umd
* [ ] npmcdn link to umd build

**Comment by Guria** [comment]
@vjeux please enable repo in travis-ci.org or gave me Owner access to this repo

**Comment by vjeux** [comment]
Travis is enabled. You should already be admin on the repo. I can't find how to give you admin access on travis :(

**Comment by Guria** [comment]
I am only collaborator but travis accepts only ones with owner rights

**Comment by vjeux** [comment]
Hmm, looks like because it's under my account I cannot give you admin rights. Do you want to create an organization for it and we move it there?

**Comment by Guria** [comment]
Hmm, yeah. It might be a reason. Do you want to create separate org? I think @christianalfoni would be glad to adopt `URLON` into https://github.com/cerebral org. We already have `url-mapper` there which depends on `URLON` and maintained by me.

**Comment by vjeux** [comment]
Happy to move it anywhere you want :)

**Comment by vjeux** [comment]
https://github.com/urlon

Seems to be unused as well.

**Comment by Guria** [comment]
Let's move it to `cerebral` org then. I am already owner on it, and we have related repos as well :)

**Comment by vjeux** [comment]
Hmm, I need to be admin on cerebral to be able to move it. I also tried to move it to you so that you can then move it to cerebral but you already have a repo with the same name (probably a fork). Can you either add me as admin temporarily or delete your repo?

**Comment by Guria** [comment]
I have deleted repo and gave you a member access as well on cerebral org

**Comment by vjeux** [comment]
https://github.com/cerebral/URLON

BOOM!

**Comment by vjeux** [comment]
I wonder if there's a way to rename it to lowercase `urlon` as well, it looks bad with all caps

**Comment by Guria** [comment]
@vjeux I have renamed it to lower-cased once you have transferred. Now it works for both case.
